name: PR

on:
  push:
    branches:
        - main
        - master
  pull_request:
    branches:
        - main
        - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12

      - name: Install Python dependencies
        run: pip install black flake8

      # Run flake8, while ignoring:
      # E501 = too long lines
      - name: Run flake8
        run: flake8 --ignore=E501 $(find ./ -name '*.py')
